### ISSUE TITLE
Find a permanent place for the demonstrator

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#1]

**Comment by imbur** [comment]
An option would be to remove a desk from the IB413 laboratory.
- [x] ask the labor admin if it is feasible to remove the faulty machines to gain free space
- [x] investigate if there are sessions that require maximum capacity (if yes, the demonstrator cannot be placed to IB413)

**Comment by imbur** [comment]
The table will most likely be placed in IL405. However, it is still a bit unsure, so leaving the issue still open.

**Comment by zsoltmazlo** [comment]
Is there any progress in this case?

**Comment by imbur** [comment]
IL405 tentatively seems suitable. Still keeping the ticket open.

**Comment by imbur** [comment]
IL405 is its current and fixed location.
