### ISSUE TITLE
TrainCurrentSpeed should be removed from the project

### ISSUE THREAD

**Issue by hegyibalint** [FTSRG/BME-MODES3#102]
As it currently seems the `TrainCurrentSpeed` proto message is not used.
We should find out if there are some hidden dependencies on it; and if there are none simply remove it from the project.

**Comment by benedekh** [comment]
And also the other unused protobuf messages. Beware to check in the cpp files also.

**Comment by benedekh** [comment]
Files are changed, we have to rebuild the xpressnetbridge yet. [remove-unused-messages branch](https://github.com/FTSRG/BME-MODES3/tree/remove-unused-messages)

**Comment by benedekh** [comment]
Corresponding branch is merged.
