### ISSUE TITLE
Organize repository layout

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#19]
BME-MoDeS3 
- src
  - components
  - messaging
  - transport
- config-management
- docs

**Comment by imbur** [comment]
I see there are some deviations from the layout proposed above. @hegyibalint @baloghlaszlo @benedekh please post the chosen new layout plan, and close the ticket.

**Comment by benedekh** [comment]
@imbur /config-management and /docs are not uploaded so their folders are missing yet.

In the /src folder, codes are separeted by language (e.g. java, cpp, js) and placed accordingly.
