### ISSUE TITLE
Missing segment electronics parts

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#29]
- [x] finish wiring of S88
- [x] S88 interpreter device
- [x] wiring all turnout actuator device to their associated BeagleBone

**Comment by imbur** [comment]
Please maintain this issue - I assume the first two subtasks are done.

**Comment by zsoltmazlo** [comment]
No, not yet.

Sincerely,
Zsolt Mázló

**Comment by zsoltmazlo** [comment]
Testing today this circuit we are came to the conclusion that the first module not responding for our signals, but checking on the code I made a recognition that we only make 24 cycle of S88, which need to increment to 32 (https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/cpp/hu.bme.mit.inf.modes3.components.soc/s88/s88.h, SOC_CYCLE_COUNT define)
