### ISSUE TITLE
Programmed train control

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#3]
Provide support for programmatic control of both the trains and the turnouts. As we discussed before in person, the task should cover the following steps:
- [x] Define the operations for the trains an the turnouts
- [x] Implement a "dispatcher" application that is able to execute commands on the table
- [ ] Create a java jar and C library for application developers
- [ ] Extract the parameters of the communication to a configuration file (e.g. topic passwords, broker IP, etc...)

**Comment by imbur** [comment]
@Chorithian please maintain this ticket, and close if done.

**Comment by hegyibalint** [comment]
#51 redefines the issue.
