### ISSUE TITLE
Update pin allocation

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#36]
Update the control methods which disable/enable section or set the turnout straight/divergent according to the new pinout headers, as soon as the corresponding PCB’s are manufactured.

**Comment by benedekh** [comment]
Use decimal Strings instead of HEX Strings in numberings. See [settings.json](https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/java/components/hu.bme.mit.inf.modes3.components.bbb/src/main/resources/conf/settings.json) as an example.

**Comment by hegyibalint** [comment]
Pin allocation updated by @zsoltmazlo, and included in the wiki.
