### ISSUE TITLE
Write unit tests for the framework components

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#37]

**Comment by benedekh** [comment]
@baloghlaszlo please comment and write unit tests for code implemented in the [hu.bme.mit.inf.modes3.messaging.communication](https://github.com/FTSRG/BME-MODES3/tree/gen3-arch/src/java/messaging/hu.bme.mit.inf.modes3.messaging.communication) project. Examples are provided in the  [hu.bme.mit.inf.modes3.components.bbb](https://github.com/FTSRG/BME-MODES3/tree/gen3-arch/src/java/components/hu.bme.mit.inf.modes3.components.bbb) project.

**Comment by baloghlaszlo** [comment]
Issue closed with de7b72ea8434aa48a4a570d73d87f7b4e0efc192
