### ISSUE TITLE
Implement Raspberry Pi UART -> ZMQ communication

### ISSUE THREAD

**Issue by benedekh** [FTSRG/BME-MODES3#45]
The byte[] -> ZMQ messages about the sections occupancy is already implemented (related commit e0c7f55df5ba64826a8db94ae4de3abc74ce1f5b). Only the 'how to get the byte[] over UART in Java' part needs to be done.

**Comment by baloghlaszlo** [comment]
Note: Someone should create a _real_ implementation of the [IS88CommunicationReader](https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/java/components/hu.bme.mit.inf.modes3.components.occupancyquery/src/main/java/hu/bme/mit/inf/modes3/components/occupancyquery/IS88CommunicationReader.xtend)

**Comment by benedekh** [comment]
Closed by 0d72c07
