### ISSUE TITLE
Find out why VIATRA returns with EObjects instead of the specific types

### ISSUE THREAD

**Issue by baloghlaszlo** [FTSRG/BME-MODES3#50]
This could help removing unnecessary casts from the code of the [SafetyLogic](https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/java/components/safetylogic/hu.bme.mit.inf.modes3.components.safetylogic.systemlevel.event/src/main/java/hu/bme/mit/inf/safetylogic/event/SafetyLogic.xtend) and its [ModelUtil](https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/java/components/safetylogic/hu.bme.mit.inf.modes3.components.safetylogic.systemlevel.event/src/main/java/hu/bme/mit/inf/safetylogic/event/ModelUtil.xtend)

**Comment by bergmanngabor** [comment]
Congrats for figuring this one out.
