### ISSUE TITLE
DCC-PC interface based train control

### ISSUE THREAD

**Issue by hegyibalint** [FTSRG/BME-MODES3#51]
- [x] Test the PC interface on the new board
- [x] Create a tightly coupled C++ based MQTT/Protobuf stack
- [x] Implement command/state features
- [x] Test the communication between this and other components

**Comment by benedekh** [comment]
@Chorithian how is this issue going? May you give a status report on it?

**Comment by Chorithian** [comment]
Core features are done, waiting for @baloghlaszlo's module to be ready to test the two modules communication.

**Comment by imbur** [comment]
@Chorithian was the testing done?

**Comment by imbur** [comment]
Tested by operation.
