### ISSUE TITLE
Prepare the SOC Arduino

### ISSUE THREAD

**Issue by hegyibalint** [FTSRG/BME-MODES3#52]
To test the implementation, we need the Arduino which can act as a gateway between S88 and the Raspberry Pi.
- [ ] Rewrite the code in terms of communication, to use UART instead of Ethernet
- [ ] Wire the Arduino with it's Raspberry Pi

This is a child issue of #45

**Comment by zsoltmazlo** [comment]
We decided to send the raw binary data over UART as a byte stream with the format below:
[header] [data3 2 1 0] [data 3 2 1 0 repeated] [header]... 

For exp: [0xFF...0xFF (7 times) 0xAA]  [0 0 10 0] [0 0 10 0]  which means that only segment number 13 is occupied.
