### ISSUE TITLE
Write UART handling code to receive SOC messages

### ISSUE THREAD

**Issue by hegyibalint** [FTSRG/BME-MODES3#53]
The libblack library should support UART.

This issue is the child issue of #45

**Comment by benedekh** [comment]
Closed by 0d72c079623d2bff5b9f23e17b19cca5713fe680

**Comment by benedekh** [comment]
Reopened due to changes in: https://github.com/FTSRG/BME-MODES3/issues/52#issuecomment-249671337

**Comment by benedekh** [comment]
Implementation and testing from python via USB and UART is done. Test is needed with the Arduino SOC yet.

**Comment by benedekh** [comment]
Closed by 41fd9c606651f173e22e68b41b5ec16583db4718
