### ISSUE TITLE
Generated protobuf java interfaces are not in a source folder

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#67]
It seems that for project `hu.bme.mit.inf.modes3.messaging.proto` the `build.gradle` will not place the generated java files into an Eclipse source folder.

**Comment by baloghlaszlo** [comment]
Gradle generates the files into the `src/main/java` folder. As we currently gitignore the .classpath files, Eclipse does not know directly that these folders are source folders.
The most likely scenario is the following:
- Eclipse reads the gradle settings, and sees, that all `src/main/java` folder are source folders
- Eclipse realizes, that this project has no such folder, so ignores the previous rule
- Later we generate the protobuf classes with gradle and it creates the folder
- Eclipse doesn't realize that the new folder which has just been created should be a source folder

To test out my assumptions, we should download the entire repository into a fresh eclipse, use gradle to build the sources, and use the `Refresh Gradle Projects` command inside Eclipse, and see if this is this issue. Also this is a one time issue, so we could solve it by not ignoring the classpath or by simply adding some lines into the devguide to manually add this folder into the source folders after the first gradle build has been made.

**Comment by imbur** [comment]
Protobuf will not be used after refactoring.
