### ISSUE TITLE
Error executing EValidator in Viatra project

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#68]
During development environment setup, an error saying "Error executing EValidator" appears on the `hu.bme.mit.inf.modes3.components.safetylogic.systemlevel.patterns` project.
(Current workaround: deleting the markers, for the error has no effect on the generated code.)

**Comment by baloghlaszlo** [comment]
This is most likely to be caused by not having the VIATRA and/or plugin nature on the project.
Simply adding the nature, cleaning the workspace, restarting Eclipse, and building solves this issue.
This issue is similar to this http://www.eclipse.org/forums/index.php/t/490152/
