### ISSUE TITLE
3D printed houses for sensors

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#79]

**Comment by zsoltmazlo** [comment]
@simon5521  if you can provide an estimated dimensions for the PCB, I can start to design the 3D model.

**Comment by imbur** [comment]
@simon5521 @zsoltmazlo this ticket is also ready to close, I assume.

**Comment by hegyibalint** [comment]
We bought 3rd party houses instead of printing, so this is solved.
