### ISSUE TITLE
Turnout control safety check

### ISSUE THREAD

**Issue by hegyibalint** [FTSRG/BME-MODES3#8]
If the master becomes the responsible unit of the turnout control, a new feature can be added to check the occupation of the turnout before setting it. With this feature, the master can make sure no train is on the turnout in the moment of switching.

**Comment by imbur** [comment]
What I understood from the description: extend the manual multimaus-based control with a foolproof mechanism regarding turnouts. Is this the main objective?

**Comment by hegyibalint** [comment]
Exactly.

**Comment by imbur** [comment]
@Chorithian @hegyibalint please update this issue.

**Comment by benedekh** [comment]
Thx, I deleted the duplicate #96
