### ISSUE TITLE
3D printed container

### ISSUE THREAD

**Issue by zsoltmazlo** [FTSRG/BME-MODES3#81]
The very first model are already created:
![container-design](https://user-images.githubusercontent.com/6101832/29497557-87c2058e-85ea-11e7-8a46-127f895f55c1.png)
![container-design-parts](https://user-images.githubusercontent.com/6101832/29497558-89ad5c0e-85ea-11e7-9f6a-cdfec4ed5038.png)
![container-design-assembled](https://user-images.githubusercontent.com/6101832/29497560-8b336d16-85ea-11e7-9818-373227bc0c6d.png)

Here we can discuss these plans and update the model.

**Comment by vorosa** [comment]
Tetszik! A kamera cserélhető lesz (csak ha esetleg elromlik)?

**Comment by zsoltmazlo** [comment]
Why would you close this issue? 

Otherwise, the slot for the camera is designed exactly for [this type of camera](https://thepihut.com/products/zerocam-fisheye-camera-for-raspberry-pi-zero?variant=36696831121), which can be modified if we can find the final camera, but these cameras are differ so much that we can only pick one.

**Comment by vorosa** [comment]
Ok, that camera is changeable :)

**Comment by imbur** [comment]
The container now works perfectly.
