### ISSUE TITLE
Merge openCV to Modes

### ISSUE THREAD

**Issue by benedekh** [FTSRG/BME-MODES3#92]
From https://github.com/FuzesiMate/ComputerVision/tree/jeckson_build/computer_vision_framework to `src/cpp/computer_vision_framework` as a Pull Request.

**Comment by zsoltmazlo** [comment]
This issue is a little bit misleading, we do not want to merge the whole opencv project into this repo, only our computer vision component.

**Comment by benedekh** [comment]
Closed by 31cfd30
